import type { GoTrainRoute, GoTrainStaticData, GoTrainStop, GoTrainTrip } from '@/types/go-train';

// Static snapshot generated by scripts/build-gtfs-static.js
const staticData = require('../data/go-train-static.json') as GoTrainStaticData;

export const goTrainData = staticData;

const stopById = new Map<string, GoTrainStop>(goTrainData.stops.map((stop) => [stop.stopId, stop]));
const routeById = new Map<string, GoTrainRoute>(goTrainData.routes.map((route) => [route.routeId, route]));

type TripOption = {
  tripId: string;
  headsign: string;
  directionId: string;
  departureTime: string;
  arrivalTime: string;
  departureSeconds: number;
  arrivalSeconds: number;
  durationMinutes: number;
};

export function secondsSinceMidnight(date: Date = new Date()): number {
  return date.getHours() * 3600 + date.getMinutes() * 60 + date.getSeconds();
}

export function formatServiceDate(yyyymmdd: string): string {
  if (!/^\d{8}$/.test(yyyymmdd)) {
    return yyyymmdd;
  }

  const isoDate = `${yyyymmdd.slice(0, 4)}-${yyyymmdd.slice(4, 6)}-${yyyymmdd.slice(6, 8)}`;
  const parsed = new Date(`${isoDate}T00:00:00`);
  if (Number.isNaN(parsed.getTime())) {
    return yyyymmdd;
  }

  return parsed.toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

export function formatGtfsTime(time: string): string {
  const match = /^(\d{1,3}):(\d{2})/.exec(time ?? '');
  if (!match) {
    return '--:--';
  }

  const hours = Number(match[1]);
  const minutes = match[2];
  const dayOffset = Math.floor(hours / 24);
  const hours24 = hours % 24;
  const hours12 = hours24 % 12 || 12;
  const meridiem = hours24 >= 12 ? 'PM' : 'AM';
  const baseTime = `${hours12}:${minutes} ${meridiem}`;

  return dayOffset > 0 ? `${baseTime} (+${dayOffset}d)` : baseTime;
}

export function searchRoutes(query: string): GoTrainRoute[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) {
    return goTrainData.routes;
  }

  return goTrainData.routes.filter((route) => {
    return (
      route.routeShortName.toLowerCase().includes(normalized) ||
      route.routeLongName.toLowerCase().includes(normalized)
    );
  });
}

export function getRouteById(routeId: string | null): GoTrainRoute | null {
  if (!routeId) {
    return null;
  }
  return routeById.get(routeId) ?? null;
}

export function getStopById(stopId: string | null): GoTrainStop | null {
  if (!stopId) {
    return null;
  }
  return stopById.get(stopId) ?? null;
}

export function getRouteStops(routeId: string | null): GoTrainStop[] {
  if (!routeId) {
    return [];
  }

  const stopIds = goTrainData.routeStops[routeId] ?? [];
  return stopIds
    .map((stopId) => stopById.get(stopId))
    .filter((stop): stop is GoTrainStop => Boolean(stop));
}

export function searchStopsOnRoute(
  routeId: string | null,
  query: string,
  excludedStopId?: string | null,
): GoTrainStop[] {
  const allStops = getRouteStops(routeId).filter((stop) => stop.stopId !== excludedStopId);
  const normalized = query.trim().toLowerCase();
  if (!normalized) {
    return allStops;
  }

  return allStops.filter((stop) => {
    return (
      stop.stopName.toLowerCase().includes(normalized) ||
      stop.stopId.toLowerCase().includes(normalized)
    );
  });
}

function findTripSegment(
  trip: GoTrainTrip,
  startStopId: string,
  endStopId: string,
): Omit<TripOption, 'tripId' | 'headsign' | 'directionId'> | null {
  let startStopTimeIndex = -1;
  for (let i = 0; i < trip.stopTimes.length; i += 1) {
    if (trip.stopTimes[i].stopId === startStopId) {
      startStopTimeIndex = i;
      break;
    }
  }

  if (startStopTimeIndex < 0) {
    return null;
  }

  let endStopTimeIndex = -1;
  for (let i = startStopTimeIndex + 1; i < trip.stopTimes.length; i += 1) {
    if (trip.stopTimes[i].stopId === endStopId) {
      endStopTimeIndex = i;
      break;
    }
  }

  if (endStopTimeIndex < 0) {
    return null;
  }

  const startStopTime = trip.stopTimes[startStopTimeIndex];
  const endStopTime = trip.stopTimes[endStopTimeIndex];

  const rawDuration = endStopTime.arrivalSeconds - startStopTime.departureSeconds;
  const durationMinutes = Math.max(1, Math.round(rawDuration / 60));

  return {
    departureTime: startStopTime.departureTime,
    arrivalTime: endStopTime.arrivalTime,
    departureSeconds: startStopTime.departureSeconds,
    arrivalSeconds: endStopTime.arrivalSeconds,
    durationMinutes,
  };
}

export function findTripsBetweenStops({
  routeId,
  startStopId,
  endStopId,
  nowSeconds,
  limit = 12,
}: {
  routeId: string | null;
  startStopId: string | null;
  endStopId: string | null;
  nowSeconds: number;
  limit?: number;
}): TripOption[] {
  if (!routeId || !startStopId || !endStopId || startStopId === endStopId) {
    return [];
  }

  const routeTrips = goTrainData.routeTrips[routeId] ?? [];
  const segments: TripOption[] = [];

  for (const trip of routeTrips) {
    const segment = findTripSegment(trip, startStopId, endStopId);
    if (!segment) {
      continue;
    }

    segments.push({
      tripId: trip.tripId,
      headsign: trip.headsign,
      directionId: trip.directionId,
      ...segment,
    });
  }

  segments.sort((a, b) => a.departureSeconds - b.departureSeconds);

  const upcoming = segments.filter((segment) => segment.departureSeconds >= nowSeconds);
  const source = upcoming.length > 0 ? upcoming : segments;

  return source.slice(0, limit);
}
